services:
  palworld:
    build:
      dockerfile: ./Dockerfile.arm
    restart: unless-stopped
    ports:
      - '8211:8211/udp'
      - '27015:27015/udp'
    env_file:
      - path: .env
        required: true
    volumes:
      - './palworld:/palworld/'
